### ISSUE TITLE
InvalidSessionAccessException: Attempted to access the ARCore Session while not connected.

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/experimental-ARInterface#1]
Running ARCore, on a pixel. Android 8.1
Unity 2017.2.0f3

relevant log:

```
11-01 12:10:22.026 24032-24100/com.unity.arscale E/Unity: AndroidJavaException: java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
                                                          java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
                                                              at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
                                                              at android.app.BackStackRecord.add(BackStackRecord.java:414)
                                                              at com.unity3d.player.UnityAndroidPermissions.RequestPermissionAsync(UnityAndroidPermissions.java:66)
                                                              at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                              at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
                                                              at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:164)
                                                              at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
                                                            at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:24 
                                                            at UnityEngine.AndroidJNISaf
11-01 12:10:22.078 24032-24100/com.unity.arscale D/Unity: Sensor :        Accelerometer ( 1) ; 0.004788 / 0.00s ; BMI160 accelerometer / Bosch 
11-01 12:10:22.082 24032-24100/com.unity.arscale D/Unity: Choreographer available: Enabling VSYNC timing
11-01 12:10:22.175 24032-24100/com.unity.arscale E/Unity: InvalidSessionAccessException: Attempted to access the ARCore Session while not connected.
                                                            at GoogleARCoreInternal.SessionManager.get_Instance () [0x00022] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\GoogleARCore\SDK\Scripts\Managers\SessionManager.cs:48 
                                                            at UnityARInterface.ARCoreInterface.Update () [0x00001] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\UnityARInterface\Scripts\ARCoreInterface.cs:273 
                                                            at UnityARInterface.ARController.Update () [0x00007] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\UnityARInterface\Scripts\ARController.cs:130 
                                                           
                                                          (Filename: C Line: 0)
11-01 12:10:22.179 24032-24100/com.unity.arscale E/Unity: InvalidSessionAccessException: Attempted to access the ARCore Session while not connected.
                                                            at GoogleARCoreInternal.SessionManager.get_Instance () [0x00022] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\GoogleARCore\SDK\Scripts\Managers\SessionManager.cs:48 
                                                            at GoogleARCore.Frame.get_PointCloud () [0x00001] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\GoogleARCore\SDK\Scripts\Frame.cs:98 
                                                            at UnityARInterface.ARCoreInterface.TryGetPointCloud (UnityARInterface.PointCloud& pointCloud) [0x00001] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\UnityARInterface\Scripts\ARCoreInterface.cs:146 
                                                            at UnityARInterface.ARPointCloudVisualizer.Update () [0x0000c] in C:\Users\bhadriche\Desktop\experimental-ARInterface\Assets\UnityARInterface\Scripts\ARPointCloudVisualizer.cs:37 
                                                           
                                                          (Filename: C Line: 0)
```

**Comment by iBicha** [comment]
Running the ARCode demo (HelloAR) throws something similar.
Which is weird because I ran ARCore demo before, at lease before I updated the system.
Could it be the Android version?

```
11-01 12:35:18.323 29776-29793/com.unity.arscale E/Unity: AndroidJavaException: java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
                                                          java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
                                                              at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
                                                              at android.app.BackStackRecord.add(BackStackRecord.java:414)
                                                              at com.unity3d.player.UnityAndroidPermissions.RequestPermissionAsync(UnityAndroidPermissions.java:66)
                                                              at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                              at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
                                                              at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:164)
                                                              at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
                                                            at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:24 
                                                            at UnityEngine.AndroidJNISaf
11-01 12:35:18.453 29776-29793/com.unity.arscale D/Unity: Sensor :        Accelerometer ( 1) ; 0.004788 / 0.00s ; BMI160 accelerometer / Bosch 
11-01 12:35:18.456 29776-29793/com.unity.arscale D/Unity: Choreographer available: Enabling VSYNC timing
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err: com.google.atap.tangoservice.TangoErrorException
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err:     at com.google.atap.tangoservice.Tango.throwTangoExceptionIfNeeded(Tango.java:1533)
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err:     at com.google.atap.tangoservice.Tango.getPoseAtTime(Tango.java:874)
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err:     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err:     at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
11-01 12:35:18.501 29776-29793/com.unity.arscale W/System.err:     at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
11-01 12:35:18.502 29776-29793/com.unity.arscale W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-01 12:35:18.502 29776-29793/com.unity.arscale W/System.err:     at android.os.Looper.loop(Looper.java:164)
11-01 12:35:18.502 29776-29793/com.unity.arscale W/System.err:     at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)

```

**Comment by timm-unity** [comment]
A few people over on the ARCore forums have reported that as well. As far as I can tell, you need to use an API level less than 26 (try 24). See also https://forum.unity.com/threads/arcore-unity-camera-permissions-dialog-never-shown.497987/#post-3237676

**Comment by iBicha** [comment]
Oh, I didn't think of manually allowing the camera. I didnt even rebuild, and it worked. I build with API  24 does it. I'll close since this is not related to  ARInterface itself.
Thanks.

**Comment by timm-unity** [comment]
Yeah, that's fair. We don't do any error checking -- just StartService and hope for the best. We should stop trying to run the update loop if StartService fails. That's a bit different from this issue though, so I'll make a separate one for it.

**Comment by timm-unity** [comment]
@iBicha See https://github.com/Unity-Technologies/experimental-ARInterface/issues/2
